# Generated by Django 4.2.6 on 2023-10-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='gpx_track',
            field=models.FileField(blank=True, null=True, upload_to='gpx_tracks/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='event_photos/'),
        ),
    ]
