# Generated by Django 4.2.6 on 2023-10-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_alter_event_gpx_track_alter_event_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
