version: '3'

services:
  postgres:
    image: postgres:16.0
    container_name: lets-take-a-ride
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

#  redis:
#    image: redis:5
#    ports:
#      - "6379:6379"
#    restart: always

volumes:
  postgres_data:
