name: Build and deploy container app to Azure Web App - lets-backend

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: letsbackend.azurecr.io
        username: ${{ secrets.AzureAppService_ContainerUsername_5b817890bcd94238bf0eb4231089d556 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_77a1c9ba82b645dd98df22ed7a2a1f0a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: letsbackend.azurecr.io/backend_web:latest
        file: ./backend/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'lets-backend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_419eb1df8a104de1946db09cecae9c2d }}
        images: 'letsbackend.azurecr.io/backend_web:latest'
